bot:
  token: ${BOT_TOKEN}
  teams:
    Summer Camp:
      enabled: true
      teamId: 13380
      chatId: -5288458918   # - настоящий чат
    Summer Camp 2:
      enabled: true
      teamId: 18820
      chatId: -1002683003320